=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xsds/ComponentConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License. -->
 
 
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="hydrograph/ui/ComponentConfig"
	xmlns:tns="hydrograph/ui/ComponentConfig" elementFormDefault="qualified" 
	xmlns:cnst="hydrograph/ui/constant">
	
	<import schemaLocation="Common.xsd"
		namespace="hydrograph/ui/constant" />
		
	<element name="Config">
		<complexType>
			<sequence>
				<element name="component" type="tns:Component" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Component">
		<sequence>
			<element name="category" type="cnst:category_type" maxOccurs="1" minOccurs="1" />
			<element name="port" type="tns:IOPort" maxOccurs="1" minOccurs="1" />
			<element name="property" type="tns:Property" maxOccurs="unbounded" minOccurs="0" />
			<element name="policy" type="tns:Policy" maxOccurs="unbounded" minOccurs="0" /> 
			<element name="operations" type="tns:Operations" maxOccurs="1" minOccurs="0" /> 
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="acronym" type="string" use="optional" default=""></attribute>
		<attribute name="nameInPalette" type="string" use="required"></attribute>
		<attribute name="defaultNamePrefix" type="string" use="required"></attribute>
		<attribute name="paletteIconPath" type="string" use="required"></attribute>
		<attribute name="canvasIconPath" type="string" use="required"></attribute>
		<attribute name="description" type="string" use="required"></attribute>
		<attribute name="helpFilePath" type="string" use="required"></attribute>
	</complexType>


	<complexType name="Property">
		<sequence>
			<element name="validator" type="cnst:validators" maxOccurs="unbounded" minOccurs="0"/>
		</sequence>
		<attribute name="type" type="cnst:property_type" use="required" />
		<attribute name="renderer" type="cnst:property_renderer" use="required" />
		<attribute name="dataType" type="cnst:data_type" use="required" />
		<attribute name="name" type="string" use="required" />
		<attribute name="value" type="string" use="optional" />
		<attribute name="group" type="cnst:group" use="required" />
		<attribute name="subGroup" type="cnst:sub_group" use="required" /> 
		<attribute name="showAsTooltip" type="cnst:showAsTooltip" use="required" />
		<attribute name="tooltipDataType" type="cnst:tooltipDataType" use="required" />
		<attribute name="propertyHelpText" type="string" use="optional" />   
		<attribute name="usage" type="cnst:usage" use="optional" />  
	</complexType>

	<complexType name="IOPort">
		<sequence>
			<element name="portSpecification" type="tns:PortSpecification" maxOccurs="unbounded" minOccurs="1"/>
		</sequence>
	</complexType>

 	<complexType name="PortSpecification">
 		<sequence>
			<element name="port" type="tns:PortInfo" maxOccurs="unbounded" minOccurs="0" />
		</sequence>
		
		<attribute name="numberOfPorts" type="int" use="required" />
		<attribute name="portAlignment" type="cnst:PortAlignment" use="required" />	
		<attribute name="changePortCountDynamically" type="boolean" use="optional" default="false"/>	
		<attribute name="allowMultipleLinks" type="boolean" use="required" />
		<attribute name="linkMandatory" type="boolean" use="required"/>	
	</complexType>
	
	<complexType name="PortInfo">
		<attribute name="sequenceOfPort" type="int" use="required" />
		<attribute name="typeOfPort" type="cnst:PortType" use="required" />
		<attribute name="portTerminal" type="string" use="required"/>
		<attribute name="labelOfPort" type="string" use="required"/>	
	</complexType>	

	 <complexType name="Policy">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="0" />
			<element name="value" type="string" maxOccurs="1" minOccurs="0" />
		</sequence>
	</complexType>
	
	 <complexType name="Operations">
		 <sequence>
			<element name="interface" type="tns:TypeInfo" maxOccurs="1" minOccurs="0" />
			<element name="stdOperation" type="tns:TypeInfo" maxOccurs="unbounded" minOccurs="0" />
		</sequence>
	</complexType>
	
	<complexType name="TypeInfo">
			<attribute name="name" type="string"/>
			<attribute name="class" type="string"/>
	</complexType>
	
</schema>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/removedups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/removedups_palette.png" canvasIconPath="/icons/removedups_canvas.png"
		name="RemovedupsComponent" nameInPalette="Remove Dups" defaultNamePrefix="RmDups" 
		description="Removes duplicates in the input data."
		helpFilePath="/hydrograph.ui.help/html/Components/Remove_Dups.html"
		acronym="RmDup">
		<tns:category>STRAIGHTPULL</tns:category>
		<tns:port>
			<tns:portSpecification numberOfPorts="1" portAlignment="left" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="in"  labelOfPort="in0" portTerminal="in0" />
			</tns:portSpecification>
			<tns:portSpecification  numberOfPorts="1" portAlignment="right" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="out" labelOfPort="out0" portTerminal="out0" />
			</tns:portSpecification>
			<tns:portSpecification  numberOfPorts="1" portAlignment="bottom" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="false">
				<tns:port sequenceOfPort="0" typeOfPort="unused" labelOfPort="un0" portTerminal="unused0" />
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
				
		<tns:property dataType="string" name="schema" renderer="STRAIGHT_SCHEMA_WIDGET" type="USER"
			group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="REQUIRED">
			<tns:validator>SCHEMA_GRID_VALIDATOR</tns:validator>
		</tns:property>	
		
		<tns:property dataType="string" name="Key_fields" renderer="COLUMN_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="OPTIONAL" propertyHelpText="Fields used for grouping.">
			<tns:validator>KEY_FIELDS_VALIDATOR</tns:validator>
		</tns:property>
			
		<tns:property dataType="string" name="Secondary_keys" renderer="SECONDARY_COLUMN_KEYS_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="OPTIONAL" propertyHelpText="Fields used for sorting within the groups.">
			<tns:validator>SECONDARY_KEY_VALIDATION</tns:validator>
			</tns:property>

		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="Used to override runtime Hadoop configurations specific \nto this component at run time." >
		<tns:validator>RUNTIME_PROPERTY_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="retention_logic"
			value="First" renderer="RETENTION_LOGIC_WIDGET" type="USER" showAsTooltip="TRUE"
			tooltipDataType="TEXT" usage="OPTIONAL" propertyHelpText="Retains record values as per specific selection."/>
			
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence \nof this component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
		<tns:property dataType="string" name="Propogate" renderer="PROPOGATE_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="OPTIONAL" propertyHelpText="Specifies propagating attributes from previous component in the job flow.">
		</tns:property>
	</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/filter_palette.png" canvasIconPath="/icons/filter_canvas.png"
		name="Filter" nameInPalette="Filter" defaultNamePrefix="Filter" 
		description="Select specific records from input based on filter condition in the operation class."
		helpFilePath="/hydrograph.ui.help/html/Components/Filter.html"
		acronym="Fltr">
		<tns:category>TRANSFORM</tns:category>
		<tns:port>
			<tns:portSpecification  numberOfPorts="1" portAlignment="left" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true" >
				<tns:port sequenceOfPort="0" typeOfPort="in" labelOfPort="in0" portTerminal="in0" />
			</tns:portSpecification>
			<tns:portSpecification  numberOfPorts="1" portAlignment="right" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="out" labelOfPort="out0" portTerminal="out0" />
			</tns:portSpecification>
			<tns:portSpecification  numberOfPorts="1" portAlignment="bottom" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="unused" labelOfPort="un0" portTerminal="unused0" />
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="schema" renderer="STRAIGHT_SCHEMA_WIDGET" type="USER"
			group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="REQUIRED">
			<tns:validator>SCHEMA_GRID_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="filterLogic" renderer="FILTER_LOGIC" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="OPTIONAL" propertyHelpText="Specify java class for performing the Filter operation.#Specify expression for performing Filter operation.">
			<tns:validator>FILTER_DATA_VALIDATION</tns:validator>
		</tns:property>
			
		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="Used to override runtime Hadoop configurations \nspecific to this component at run time.">
		 <tns:validator>RUNTIME_PROPERTY_VALIDATOR</tns:validator>
		</tns:property>

		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence \nof this component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
         
         <tns:property dataType="string" name="Propogate" renderer="PROPOGATE_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="OPTIONAL" propertyHelpText="Specifies propagating attributes from previous component in the job flow.">
		</tns:property>
	
	<tns:operations>
		<tns:interface class="hydrograph.engine.transformation.userfunctions.base.FilterBase"
			name="FILTER" />
	</tns:operations>
	</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/runprogram.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->

<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/runprogram_palette.png" canvasIconPath="/icons/runprogram_canvas.png"
		name="RunProgram" nameInPalette="Run Program" defaultNamePrefix="RunProgram" 
		description="Run's command given as input"
		helpFilePath="/hydrograph.ui.help/html/Components/Run_Program.html"
		acronym="Run">
		<tns:category>COMMAND</tns:category>
			<tns:port>
			
			<tns:portSpecification numberOfPorts="0" portAlignment="bottom" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="false">
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
		
		<tns:property dataType="string" name="runcommand" value="" renderer="RUNPROGRAM_TEXT_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK"
			usage="REQUIRED" propertyHelpText="Displays command provided by user">
			<tns:validator>NON_EMPTY_STRING_VALIDATOR</tns:validator>
		</tns:property>
			
		
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence \nof this component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
	</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/partitionbyexpression.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->


<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/partitionbyexpression_palette.png"
		canvasIconPath="/icons/partitionbyexpression_canvas.png" name="PartitionByExpression"
		nameInPalette="Partition By Expression" defaultNamePrefix="PartByExp"
		description="distributes data records to its output partitions based on evaluation of expression specified."
		helpFilePath="/hydrograph.ui.help/html/Components/Partition_By_Expression.html" acronym="PartXp">
		<tns:category>TRANSFORM</tns:category>
		<tns:port>
			<tns:portSpecification numberOfPorts="1"
				portAlignment="left" changePortCountDynamically="false"
				allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="in" labelOfPort="in0"
					portTerminal="in0" />
			</tns:portSpecification>

			<tns:portSpecification numberOfPorts="1"
				portAlignment="bottom" changePortCountDynamically="false"
				allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="unused"
					labelOfPort="un0" portTerminal="unused0" />
			</tns:portSpecification>

			<tns:portSpecification numberOfPorts="2"
				portAlignment="right" changePortCountDynamically="true"
				allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="out" labelOfPort="out0"
					portTerminal="out0" />
				<tns:port sequenceOfPort="1" typeOfPort="out" labelOfPort="out1"
					portTerminal="out1" />
			</tns:portSpecification>
		</tns:port>

		<tns:property dataType="string" name="name"
			renderer="COMPONENT_NAME_WIDGET" type="USER" group="GENERAL"
			subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT" usage="REQUIRED"
			propertyHelpText="Displays Name provided by the user" />

		<tns:property dataType="string" name="schema"
			renderer="STRAIGHT_SCHEMA_WIDGET" type="USER" group="SCHEMA"
			subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="TRUE"
			tooltipDataType="LIST" usage="REQUIRED">
			<tns:validator>SCHEMA_GRID_VALIDATOR</tns:validator>

		</tns:property>

		<tns:property dataType="string" name="outPortCount"
			value="2" renderer="PARTITION_COMPONENT_OUTPUT_COUNT_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE"
			tooltipDataType="TEXT" usage="REQUIRED"
			propertyHelpText="Specifies number of output partitions to be created. Default is 2.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>

		<tns:property dataType="string" name="filterLogic" renderer="FILTER_LOGIC" type="USER" group="GENERAL"
			subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK"
			usage="REQUIRED"
			propertyHelpText="Specify java class for performing the partitioning.#Specify expression for performing the partitioning.">
			<tns:validator>FILTER_DATA_VALIDATION</tns:validator>
		</tns:property>

		<tns:property dataType="string" name="runtime_properties"
			renderer="RUNTIME_PROPERTIES_WIDGET" type="USER" group="GENERAL"
			subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL"
			propertyHelpText="Used to overwrite runtime Hadoop configurations specific to this component on runtime." />


		<tns:property dataType="string" name="batch" value="0"
			renderer="BATCH_WIDGET" type="USER" group="GENERAL" subGroup="CONFIGURATION"
			showAsTooltip="TRUE" tooltipDataType="TEXT" usage="REQUIRED"
			propertyHelpText="Specifies execution sequence of this component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>

		<tns:property dataType="string" name="Propogate"
			renderer="PROPOGATE_WIDGET" type="USER" group="GENERAL" subGroup="CONFIGURATION"
			showAsTooltip="TRUE" tooltipDataType="TEXT" usage="OPTIONAL"
			propertyHelpText="Specifies propagating attributes from previous component in the job flow.">
		</tns:property>

		<tns:operations>
			<tns:interface class="hydrograph.engine.transformation.userfunctions.base.CustomPartitionExpression"
				name="PartitionByExpression" />
		</tns:operations>
	</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/inputxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License. -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/input_xml_palette.png" canvasIconPath="/icons/input_xml_canvas.png"
		name="IXml" nameInPalette="XML" defaultNamePrefix="IXML" 
		description="Used to read xml file."
		helpFilePath="/hydrograph.ui.help/html/Components/input/Input_Xml.html"
		acronym="IXML">
		<tns:category>INPUT</tns:category>
		<tns:port>
			<tns:portSpecification  numberOfPorts="1" portAlignment="right" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="out" labelOfPort="out0" portTerminal="out0" />
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
		
		<tns:property dataType="string" name="schema" renderer="XPATH_SCHEMA_WIDGET" type="USER"
			group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="REQUIRED">
			<tns:validator>XPATH_SCHEMA_GRID_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="Path" renderer="XML_FILE_PATH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK"
			usage="REQUIRED" propertyHelpText="Displays the location of the file either Remote/Local. 
			\nAllows only underscore ‘_’ and alphanumeric characters.">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="absoluteXPath" value="" renderer="XPATH_QUERY_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Xpath for the xml">
			<tns:validator>NON_EMPTY_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="rootTag" value="" renderer="ROOT_TAG_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Root tag for the xml">
			<tns:validator>NON_EMPTY_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="rowTag" value="" renderer="ROW_TAG_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Row tag for the xml">
			<tns:validator>NON_EMPTY_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="GenerateSchema"
			renderer="XML_GENERATE_SCHEMA_WIDGET" type="USER" group="GENERAL"
			subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Will be added soon.">
		</tns:property>
		
		
		<tns:property dataType="boolean" name="safe" value="False" renderer="SAFE_PROPERTY_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="When True, allows the input fields to pass \nevaluation despite of Data type mismatch.">
			<tns:validator>BOOLEAN_OR_PARAMETER_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="charset" value="UTF-8" renderer="CHARACTER_SET_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="REQUIRED" propertyHelpText="Denotes the encoding system followed by the input file.">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="Used to override runtime \nHadoop configurations specific to \nthis component at run time.">
		<tns:validator>RUNTIME_PROPERTY_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence of \nthis component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
	</tns:component>
</tns:Config>
