=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xsds/ComponentConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License. -->
 
 
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="hydrograph/ui/ComponentConfig"
	xmlns:tns="hydrograph/ui/ComponentConfig" elementFormDefault="qualified" 
	xmlns:cnst="hydrograph/ui/constant">
	
	<import schemaLocation="Common.xsd"
		namespace="hydrograph/ui/constant" />
		
	<element name="Config">
		<complexType>
			<sequence>
				<element name="component" type="tns:Component" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Component">
		<sequence>
			<element name="category" type="cnst:category_type" maxOccurs="1" minOccurs="1" />
			<element name="port" type="tns:IOPort" maxOccurs="1" minOccurs="1" />
			<element name="property" type="tns:Property" maxOccurs="unbounded" minOccurs="0" />
			<element name="policy" type="tns:Policy" maxOccurs="unbounded" minOccurs="0" /> 
			<element name="operations" type="tns:Operations" maxOccurs="1" minOccurs="0" /> 
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="acronym" type="string" use="optional" default=""></attribute>
		<attribute name="nameInPalette" type="string" use="required"></attribute>
		<attribute name="defaultNamePrefix" type="string" use="required"></attribute>
		<attribute name="paletteIconPath" type="string" use="required"></attribute>
		<attribute name="canvasIconPath" type="string" use="required"></attribute>
		<attribute name="description" type="string" use="required"></attribute>
		<attribute name="helpFilePath" type="string" use="required"></attribute>
	</complexType>


	<complexType name="Property">
		<sequence>
			<element name="validator" type="cnst:validators" maxOccurs="unbounded" minOccurs="0"/>
		</sequence>
		<attribute name="type" type="cnst:property_type" use="required" />
		<attribute name="renderer" type="cnst:property_renderer" use="required" />
		<attribute name="dataType" type="cnst:data_type" use="required" />
		<attribute name="name" type="string" use="required" />
		<attribute name="value" type="string" use="optional" />
		<attribute name="group" type="cnst:group" use="required" />
		<attribute name="subGroup" type="cnst:sub_group" use="required" /> 
		<attribute name="showAsTooltip" type="cnst:showAsTooltip" use="required" />
		<attribute name="tooltipDataType" type="cnst:tooltipDataType" use="required" />
		<attribute name="propertyHelpText" type="string" use="optional" />   
		<attribute name="usage" type="cnst:usage" use="optional" />  
	</complexType>

	<complexType name="IOPort">
		<sequence>
			<element name="portSpecification" type="tns:PortSpecification" maxOccurs="unbounded" minOccurs="1"/>
		</sequence>
	</complexType>

 	<complexType name="PortSpecification">
 		<sequence>
			<element name="port" type="tns:PortInfo" maxOccurs="unbounded" minOccurs="0" />
		</sequence>
		
		<attribute name="numberOfPorts" type="int" use="required" />
		<attribute name="portAlignment" type="cnst:PortAlignment" use="required" />	
		<attribute name="changePortCountDynamically" type="boolean" use="optional" default="false"/>	
		<attribute name="allowMultipleLinks" type="boolean" use="required" />
		<attribute name="linkMandatory" type="boolean" use="required"/>	
	</complexType>
	
	<complexType name="PortInfo">
		<attribute name="sequenceOfPort" type="int" use="required" />
		<attribute name="typeOfPort" type="cnst:PortType" use="required" />
		<attribute name="portTerminal" type="string" use="required"/>
		<attribute name="labelOfPort" type="string" use="required"/>	
	</complexType>	

	 <complexType name="Policy">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="0" />
			<element name="value" type="string" maxOccurs="1" minOccurs="0" />
		</sequence>
	</complexType>
	
	 <complexType name="Operations">
		 <sequence>
			<element name="interface" type="tns:TypeInfo" maxOccurs="1" minOccurs="0" />
			<element name="stdOperation" type="tns:TypeInfo" maxOccurs="unbounded" minOccurs="0" />
		</sequence>
	</complexType>
	
	<complexType name="TypeInfo">
			<attribute name="name" type="string"/>
			<attribute name="class" type="string"/>
	</complexType>
	
</schema>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/outputFileExcel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd">
	<tns:component paletteIconPath="/icons/fileexcel_palette.png" canvasIconPath="/icons/fileexcel_canvas.png"
		name="OFExcel" nameInPalette="File Excel" defaultNamePrefix="OFExcel" 
		description="Used to write data in Microsoft Excel Files."
		helpFilePath=""
		acronym="Excel">
		<tns:category>OUTPUT</tns:category>
		<tns:port>
			<tns:portSpecification numberOfPorts="1" portAlignment="left" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="in" labelOfPort="in0" portTerminal="in0" />
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
			
			<tns:property dataType="string" name="schema" renderer="SCHEMA_WIDGET" type="USER"
			group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="REQUIRED">
			<tns:validator>SCHEMA_GRID_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="fileName" value="" renderer="EXCEL_FILE_NAME_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays the File Name provided by the user">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="Path" renderer="EXCEL_FILE_PATH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK"
			usage="REQUIRED" propertyHelpText="Displays the location of the file either Remote/Local. \nAllows only underscore ‘_’ and alphanumeric characters.">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="workSheetName" renderer="WORKSHEET_NAME_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays the WorkSheet Name provided by the user">
			<tns:validator>WORKSHEET_NAME_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="excel_formatting" renderer="EXCEL_FORMATTING_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="OPTIONAL" propertyHelpText="Provides user to define format of header and data for the excel sheets.">
		</tns:property>
		
		<tns:property dataType="string" name="Key_fields_sort" renderer="SORT_EXCEL_COLUMNS_KEYS_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="OPTIONAL" propertyHelpText="Provides the sorting order of columns">
		</tns:property>
			
		<tns:property dataType="string" name="writeMode" value="FailIfFileExists" renderer="WRITE_MODE_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="REQUIRED" propertyHelpText="Denotes the writing mode for an Excel File.">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="stripLeadingQuote" value="True"
		renderer="STRIP_LEADING_QUOTE_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"
		usage="OPTIONAL" propertyHelpText="True specifies stripping leading single quotes and if selected False data is written to output as is to the excel.">
			<tns:validator>BOOLEAN_OR_PARAMETER_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="charset" value="UTF-8" renderer="CHARACTER_SET_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="REQUIRED" propertyHelpText="Denotes the encoding system followed by the input file.">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="autoColumnSize" value="False"
		renderer="AUTO_SIZE_COLUMN_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"
		usage="OPTIONAL" propertyHelpText="Setting this value to true will adjust the column width to fit the contents.">
			<tns:validator>BOOLEAN_OR_PARAMETER_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="runtime_properties"
			renderer="RUNTIME_PROPERTIES_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="Used to override runtime Hadoop configurations \nspecific to this component at run time." >
		<tns:validator>RUNTIME_PROPERTY_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence of \nthis component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
	</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/cumulate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/cumulate_palette.png" canvasIconPath="/icons/cumulate_canvas.png"
		name="Cumulate" nameInPalette="Cumulate" defaultNamePrefix="Cumulate" 
		description="Performs cumulate on data specified in a java operation class."
		helpFilePath="/hydrograph.ui.help/html/Components/Cumulate.html"
		acronym="Cmlt">
		<tns:category>TRANSFORM</tns:category>
		<tns:port>
			<tns:portSpecification numberOfPorts="1" portAlignment="left" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0"  typeOfPort="in" portTerminal="in0" labelOfPort="in0"/>
			</tns:portSpecification>
			<tns:portSpecification numberOfPorts="1" portAlignment="right" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="out"  portTerminal="out0" labelOfPort="out0"/>
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
		

		<tns:property dataType="string" name="schema" renderer="TRANSFORM_SCHEMA_WIDGET" type="USER"
			group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="TRUE" tooltipDataType="LIST"
         usage="REQUIRED">
			<tns:validator>TRANSFORM_SCHEMA_GRID_VALIDATOR</tns:validator>
		</tns:property>
		
		
		<tns:property dataType="string" name="Key_fields" renderer="COLUMN_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="REQUIRED" propertyHelpText="Fields used for grouping.">
			<tns:validator>KEY_FIELDS_VALIDATOR</tns:validator>
		</tns:property>
			
		<tns:property dataType="string" name="Secondary_keys" renderer="SECONDARY_COLUMN_KEYS_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="OPTIONAL" propertyHelpText="Fields used for sorting within the groups.">
		</tns:property>
		
		<tns:property dataType="string" name="operation" renderer="CUMULATE_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK"
			usage="OPTIONAL" propertyHelpText="Field Mapping view.">
			<tns:validator>TRANSFORM_MAPPING_VALIDATOR</tns:validator>
			</tns:property>

		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="Used to override runtime Hadoop configurations \nspecific to this component at run time.">
			<tns:validator>RUNTIME_PROPERTY_VALIDATOR</tns:validator>
		</tns:property>
		
			
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence \nof this component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>

		</tns:property>
		
		<tns:property dataType="string" name="Propogate" renderer="PROPOGATE_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="OPTIONAL" propertyHelpText="Specifies propagating attributes from previous component in the job flow.">
		</tns:property>
		
	
	<tns:operations>
		<tns:interface
			class="hydrograph.engine.transformation.userfunctions.base.CumulateTransformBase"
			name="CUMULATE" />
		<tns:stdOperation class="hydrograph.engine.transformation.userfunctions.cumulate.Sum"
			name="Sum" />
		<tns:stdOperation
			class="hydrograph.engine.transformation.userfunctions.cumulate.Count" name="Count" />
		<tns:stdOperation
			class="hydrograph.engine.transformation.userfunctions.cumulate.StringAppend"
			name="StringAppend" />
	</tns:operations>		
	</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/generaterecords.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/generate_records_palette.png" canvasIconPath="/icons/generate_records_canvas.png"
		name="GenerateRecords" nameInPalette="Generate Records" defaultNamePrefix="GRecords" 
		description="Generates dummy records as per the schema specified by the user."
		helpFilePath="/hydrograph.ui.help/html/Components/Generate_Records.html"
		acronym="Genrec">
		<tns:category>INPUT</tns:category>
		<tns:port>
			<tns:portSpecification  numberOfPorts="1" portAlignment="right" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="out" labelOfPort="out0" portTerminal="out0" />
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
		
		<tns:property dataType="string" name="schema" renderer="GENERATE_RECORDS_SCHEMA_WIDGET" type="USER"
			group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="REQUIRED">
			<tns:validator>SCHEMA_GRID_VALIDATOR</tns:validator>
		</tns:property>
		
		
			
		<tns:property dataType="string" name="recordCount" value="0" renderer="NO_OF_RECORDS_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specify number of records to be generated">
			<tns:validator>INTEGER_OR_PARAMETER_VALIDATOR</tns:validator>
		</tns:property>	
		
		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="Used to override runtime Hadoop configurations\n specific to this component at run time." >
		   <tns:validator>RUNTIME_PROPERTY_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence of this component in the job flow">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
	</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/inputfixedwidth.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/input_file_palette.png" canvasIconPath="/icons/input_file_canvas.png"
		name="IFixedWidth" nameInPalette="File Fixed Width" defaultNamePrefix="IFFixedWidth" 
		description="Used to read any Fixed Width text file."
		helpFilePath="/hydrograph.ui.help/html/Components/Input_File_Fixed_Width.html"
		acronym="IFxd">
		<tns:category>INPUT</tns:category>
		<tns:port>
			<tns:portSpecification  numberOfPorts="1" portAlignment="right" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="out" labelOfPort="out0" portTerminal="out0" />
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
		
		<tns:property dataType="string" name="schema" renderer="FIXED_WIDGET" type="USER"
			group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="REQUIRED">
			<tns:validator>SCHEMA_GRID_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="Path" renderer="FILE_PATH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK"
			usage="REQUIRED" propertyHelpText="Displays the location of the file \neither Remote/Local. Allows only \nunderscore ‘_’ and alphanumeric characters.">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		
		<tns:property dataType="boolean" name="safe" value="False" renderer="SAFE_PROPERTY_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="When True, allows the input fields \nto pass evaluation despite of \nData type mismatch.">
			<tns:validator>BOOLEAN_OR_PARAMETER_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="charset" value="UTF-8" renderer="CHARACTER_SET_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="REQUIRED" propertyHelpText="Denotes the encoding system \nfollowed by the input file.">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="strict" value="True"
		renderer="STRICT_CLASS_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"
		usage="OPTIONAL" propertyHelpText="When True, validates the Record Structure \nlike no. of fields, length of record, scale as \nspecified by the user.">
			<tns:validator>BOOLEAN_OR_PARAMETER_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="Used to override runtime Hadoop configurations \nspecific to this component at run time.">
		<tns:validator>RUNTIME_PROPERTY_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence \nof this component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
	</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/runsql.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 

<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd">
	<tns:component paletteIconPath="/icons/runsql_palette.png" canvasIconPath="/icons/runsql.png"
		name="RunSQL" nameInPalette="RunSQL" defaultNamePrefix="RunSQL" 
		description="Execute SQL queries on given databases"
		helpFilePath="/hydrograph.ui.help/html/Components/RunSQL.html"
		acronym="RnSQL">
		<tns:category>COMMAND</tns:category>
		<tns:port>
			<tns:portSpecification numberOfPorts="0" portAlignment="bottom" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="false">
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
		
		<tns:property dataType="string" name="databaseConnectionName" value="Oracle" renderer="DATABASE_LIST_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="REQUIRED" propertyHelpText="List of databases supported by the component">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>

		<tns:property dataType="string" name="databaseName" value="" renderer="DATABASE_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK"
			usage="REQUIRED" propertyHelpText="Database name to connect.">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>	
				
		<tns:property dataType="string" name="hostName" value="" renderer="HOST_NAME_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays the Database Host Name provided by the user">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
			
		<tns:property dataType="string" name="port" value="1521" renderer="PORT_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays the Database Port provided by the user">
			<tns:validator>PORT_VALIDATOR</tns:validator>
		</tns:property>
		
		
		<tns:property dataType="string" name="userName" value="" renderer="USER_NAME_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays the Database User Name provided by the user">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="password" value="" renderer="PASSWORD_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Password requires for connection with oracle database">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="runsqlquery" value="" renderer="RUN_SQL_QUERY_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK"
			usage="REQUIRED" propertyHelpText="Displays command provided by user">
			<tns:validator>NON_EMPTY_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence of \nthis component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
	</tns:component>
</tns:Config>
