=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xsds/ComponentConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License. -->
 
 
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="hydrograph/ui/ComponentConfig"
	xmlns:tns="hydrograph/ui/ComponentConfig" elementFormDefault="qualified" 
	xmlns:cnst="hydrograph/ui/constant">
	
	<import schemaLocation="Common.xsd"
		namespace="hydrograph/ui/constant" />
		
	<element name="Config">
		<complexType>
			<sequence>
				<element name="component" type="tns:Component" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Component">
		<sequence>
			<element name="category" type="cnst:category_type" maxOccurs="1" minOccurs="1" />
			<element name="port" type="tns:IOPort" maxOccurs="1" minOccurs="1" />
			<element name="property" type="tns:Property" maxOccurs="unbounded" minOccurs="0" />
			<element name="policy" type="tns:Policy" maxOccurs="unbounded" minOccurs="0" /> 
			<element name="operations" type="tns:Operations" maxOccurs="1" minOccurs="0" /> 
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="acronym" type="string" use="optional" default=""></attribute>
		<attribute name="nameInPalette" type="string" use="required"></attribute>
		<attribute name="defaultNamePrefix" type="string" use="required"></attribute>
		<attribute name="paletteIconPath" type="string" use="required"></attribute>
		<attribute name="canvasIconPath" type="string" use="required"></attribute>
		<attribute name="description" type="string" use="required"></attribute>
		<attribute name="helpFilePath" type="string" use="required"></attribute>
	</complexType>


	<complexType name="Property">
		<sequence>
			<element name="validator" type="cnst:validators" maxOccurs="unbounded" minOccurs="0"/>
		</sequence>
		<attribute name="type" type="cnst:property_type" use="required" />
		<attribute name="renderer" type="cnst:property_renderer" use="required" />
		<attribute name="dataType" type="cnst:data_type" use="required" />
		<attribute name="name" type="string" use="required" />
		<attribute name="value" type="string" use="optional" />
		<attribute name="group" type="cnst:group" use="required" />
		<attribute name="subGroup" type="cnst:sub_group" use="required" /> 
		<attribute name="showAsTooltip" type="cnst:showAsTooltip" use="required" />
		<attribute name="tooltipDataType" type="cnst:tooltipDataType" use="required" />
		<attribute name="propertyHelpText" type="string" use="optional" />   
		<attribute name="usage" type="cnst:usage" use="optional" />  
	</complexType>

	<complexType name="IOPort">
		<sequence>
			<element name="portSpecification" type="tns:PortSpecification" maxOccurs="unbounded" minOccurs="1"/>
		</sequence>
	</complexType>

 	<complexType name="PortSpecification">
 		<sequence>
			<element name="port" type="tns:PortInfo" maxOccurs="unbounded" minOccurs="0" />
		</sequence>
		
		<attribute name="numberOfPorts" type="int" use="required" />
		<attribute name="portAlignment" type="cnst:PortAlignment" use="required" />	
		<attribute name="changePortCountDynamically" type="boolean" use="optional" default="false"/>	
		<attribute name="allowMultipleLinks" type="boolean" use="required" />
		<attribute name="linkMandatory" type="boolean" use="required"/>	
	</complexType>
	
	<complexType name="PortInfo">
		<attribute name="sequenceOfPort" type="int" use="required" />
		<attribute name="typeOfPort" type="cnst:PortType" use="required" />
		<attribute name="portTerminal" type="string" use="required"/>
		<attribute name="labelOfPort" type="string" use="required"/>	
	</complexType>	

	 <complexType name="Policy">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="0" />
			<element name="value" type="string" maxOccurs="1" minOccurs="0" />
		</sequence>
	</complexType>
	
	 <complexType name="Operations">
		 <sequence>
			<element name="interface" type="tns:TypeInfo" maxOccurs="1" minOccurs="0" />
			<element name="stdOperation" type="tns:TypeInfo" maxOccurs="unbounded" minOccurs="0" />
		</sequence>
	</complexType>
	
	<complexType name="TypeInfo">
			<attribute name="name" type="string"/>
			<attribute name="class" type="string"/>
	</complexType>
	
</schema>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/join.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/join_palette.png" canvasIconPath="/icons/join_canvas.png"
		name="Join" nameInPalette="Join" defaultNamePrefix="Join" 
		description="Joins two or more input sources." 
		helpFilePath="/hydrograph.ui.help/html/Components/Join.html"
		acronym="Join">
		<tns:category>TRANSFORM</tns:category>
		<tns:port>
			<tns:portSpecification  numberOfPorts="2" portAlignment="left" changePortCountDynamically="true" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="in" labelOfPort="in0" portTerminal="in0" />
				<tns:port sequenceOfPort="1" typeOfPort="in" labelOfPort="in1" portTerminal="in1"/>
			</tns:portSpecification>
			<tns:portSpecification  numberOfPorts="2" portAlignment="bottom" changePortCountDynamically="true" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="unused" labelOfPort="un0" portTerminal="unused0" />
				<tns:port sequenceOfPort="1" typeOfPort="unused" labelOfPort="un1" portTerminal="unused1" />
			</tns:portSpecification>
			<tns:portSpecification  numberOfPorts="1" portAlignment="right" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="out" labelOfPort="out0" portTerminal="out0" />
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
			

		<tns:property dataType="string" name="schema" renderer="TRANSFORM_SCHEMA_WIDGET" type="USER"
			group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="REQUIRED">
			<tns:validator>TRANSFORM_SCHEMA_GRID_VALIDATOR</tns:validator>
		</tns:property>
			
		<tns:property dataType="string" name="inPortCount|unusedPortCount" value="2" renderer="JOIN_INPUT_COUNT_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies number of inputs for the Join operation. Default 2.">
		</tns:property>
			
		<tns:property dataType="string" name="join_config" renderer="JOIN_TYPE_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="REQUIRED" propertyHelpText="Specifies key fields and Join type">
			<tns:validator>JOIN_CONFIG_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="join_mapping"  renderer="JOIN_MAPPING_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK"
			usage="REQUIRED" propertyHelpText="Fields mapping view.">
			<tns:validator>JOIN_MAPPING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="Used to override runtime Hadoop configurations \nspecific to this component at run time.">
		<tns:validator>RUNTIME_PROPERTY_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence \nof this component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
		 <tns:property dataType="string" name="Propogate" renderer="PROPOGATE_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="OPTIONAL" propertyHelpText="Specifies propagating attributes from previous component in the job flow.">
		</tns:property>
	</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/outputfileparquet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/output_file_palette.png" canvasIconPath="/icons/output_file_canvas.png"
		name="OFParquet" nameInPalette="File Parquet" defaultNamePrefix="OFParquet" 
		description="Used to write a Parquet file."
		helpFilePath="/hydrograph.ui.help/html/Components/Output_File_Parquet.html"
		acronym="OFPrq">
		<tns:category>OUTPUT</tns:category>
		<tns:port>
			<tns:portSpecification numberOfPorts="1" portAlignment="left" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="in" labelOfPort="in0" portTerminal="in0" />
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED"/>
		
		<tns:property dataType="string" group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS"
			name="schema" renderer="SCHEMA_WIDGET" type="USER" showAsTooltip="FALSE"
			tooltipDataType="NONE" usage="REQUIRED">
			<tns:validator>SCHEMA_GRID_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="Path"
			renderer="FILE_PATH_WIDGET" type="USER" showAsTooltip="TRUE" tooltipDataType="LINK"
			usage="REQUIRED">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="overWrite" value="False"
			renderer="OVERWRITE_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="If ‘Overwrite’ property is true, the output location will be overwritten. Existing file / folder contents will be deleted.">
			<tns:validator>BOOLEAN_OR_PARAMETER_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="runtime_properties"
			renderer="RUNTIME_PROPERTIES_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL">
		<tns:validator>RUNTIME_PROPERTY_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
	</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/inputhivetextfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd">
	<tns:component paletteIconPath="/icons/hive_palette.png" canvasIconPath="/icons/hive_canvas.png"
		name="IHiveTextFile" nameInPalette="Hive Text File" defaultNamePrefix="IHiveTextFile" 
		description="Used to read data from Hive tables stored in delimited format."
		helpFilePath="/hydrograph.ui.help/html/Components/Input_Hive_Text.html"
		acronym="IHTxt">
		<tns:category>INPUT</tns:category>
		<tns:port>
			<tns:portSpecification  numberOfPorts="1" portAlignment="right" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="out" labelOfPort="out0" portTerminal="out0" />
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
			
			<tns:property dataType="string" name="schema" renderer="SCHEMA_WIDGET" type="USER"
			group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="REQUIRED">
			<tns:validator>SCHEMA_GRID_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="databaseName" value="" renderer="DATABASE_NAME_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays the Hive Database Name provided by the user">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
			
			<tns:property dataType="string" name="tableName" value="" renderer="TABLE_NAME_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays the Hive Table Name provided by the user">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
			
		<tns:property dataType="string" name="extractMetaStoreData" renderer="EXTRACT_METASTORE_DATA_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="OPTIONAL" propertyHelpText="Extract Hive schema,delimeter,partition keys from remote.">
		</tns:property>
		
		<tns:property dataType="string" name="externalTablePath" value="" renderer="EXTERNAL_TABLE_PATH_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="OPTIONAL" propertyHelpText="Displays the location of the file either Remote/Local.">
		</tns:property>
		
		
		<tns:property dataType="string" name="delimiter" value="|" renderer="DELIMETER_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies Delimiter present in the input file.">
			<tns:validator>NON_BLANK_STRING_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="quote" value="" renderer="QUOTE_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="OPTIONAL" propertyHelpText="Specifies Quote present in the input file.">
		</tns:property>
		
		<tns:property dataType="boolean" name="safe" value="False" renderer="SAFE_PROPERTY_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="When True, allows the input fields to pass \nevaluation despite of Data type mismatch.">
			<tns:validator>BOOLEAN_OR_PARAMETER_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="strict" value="True"
			renderer="STRICT_CLASS_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="When True, validates the Record Structure \nlike no. of fields, length of record, scale \nas specified by the user.">
			<tns:validator>BOOLEAN_OR_PARAMETER_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="partitionKeys" renderer="PARTITION_KEYS_WIDGET_INPUT_HIVE"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="OPTIONAL" propertyHelpText="Displays the user specific partition keys">
		</tns:property>
		
		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="OPTIONAL" propertyHelpText="Used to override runtime \nHadoop configurations specific to \nthis component at run time.">
		<tns:validator>RUNTIME_PROPERTY_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence of \nthis component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
	</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/outputsubjob.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/output_subjob_palette.png"
		canvasIconPath="/icons/output_subjob_canvas.png" name="OutputSubjobComponent"
		nameInPalette="Output Socket for subjob" defaultNamePrefix="OutSubjob"
		description="Represents the out sockets for a subjob."
		helpFilePath="/hydrograph.ui.help/html/Components/Dummy.html"  acronym="OSubS">
		<tns:category>SUBJOB</tns:category>

		
		<tns:port>
			<tns:portSpecification numberOfPorts="1" portAlignment="left" changePortCountDynamically="true" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="in" portTerminal="in0" labelOfPort="in0"/>
			</tns:portSpecification>
			
			<tns:portSpecification numberOfPorts="0" portAlignment="right" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
			</tns:portSpecification>
			
			<tns:portSpecification numberOfPorts="0" portAlignment="bottom" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
			</tns:portSpecification>
		</tns:port>			
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
		
		<tns:property dataType="string" name="inPortCount" value="1" renderer="INPUT_COUNT_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies number of input ports. Default 1">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
		
		</tns:component>
</tns:Config>

=== radtek/SparkETL/hydrograph.ui/hydrograph.ui.product/resources/config/xml/sort.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->
 
 
<tns:Config xmlns:tns="hydrograph/ui/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hydrograph/ui/ComponentConfig xsds/ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/sort_palette.png" canvasIconPath="/icons/sort_canvas.png"
		name="SortComponent" nameInPalette="Sort" defaultNamePrefix="Sort" 
		description="Sorts input records based on the primary and secondary key fields."
		helpFilePath="/hydrograph.ui.help/html/Components/Sort.html"
		acronym="Sort">
		<tns:category>STRAIGHTPULL</tns:category>
		<tns:port>
			<tns:portSpecification  numberOfPorts="1" portAlignment="left" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="in" labelOfPort="in0" portTerminal="in0" />
			</tns:portSpecification>
			<tns:portSpecification numberOfPorts="1" portAlignment="right" changePortCountDynamically="false" allowMultipleLinks="false" linkMandatory="true">
				<tns:port sequenceOfPort="0" typeOfPort="out"  labelOfPort="out0" portTerminal="out0" />
			</tns:portSpecification>
		</tns:port>
		
		
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DETAILS" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Displays Name provided by the user"/>
		
		<tns:property dataType="string" name="schema" renderer="STRAIGHT_SCHEMA_WIDGET" type="USER"
			group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="REQUIRED">
			<tns:validator>SCHEMA_GRID_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="Key_fields_sort" renderer="PRIMARY_COLUMN_KEYS_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LIST"
			usage="OPTIONAL" propertyHelpText="Fields used for grouping.">
			<tns:validator>SORT_KEY_FIELDS_VALIDATOR</tns:validator>
			</tns:property>
			
		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL" propertyHelpText="Used to override runtime Hadoop configurations specific \nto this component at run time.">	
				<tns:validator>RUNTIME_PROPERTY_VALIDATOR</tns:validator>
		</tns:property>
			
		<tns:property dataType="string" name="batch" value="0" renderer="BATCH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED" propertyHelpText="Specifies the execution sequence of this component in the job flow.">
			<tns:validator>INTEGER_VALIDATOR</tns:validator>
		</tns:property>
		
		<tns:property dataType="string" name="Propogate" renderer="PROPOGATE_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="OPTIONAL" propertyHelpText="Specifies propagating attributes from previous component in the job flow.">
		</tns:property>
		
	</tns:component>
</tns:Config>
